const actionTypes = {
    LOAD_VIDEOGAMES: 'LOAD_VIDEOGAMES',
    LOAD_VIDEOGAMES_ERROR: 'LOAD_VIDEOGAMES_ERROR',
    LOAD_VIDEOGAME: 'LOAD_VIDEOGAME',
    LOAD_VIDEOGAME_ERROR: 'LOAD_VIDEOGAME_ERROR',
    SET_LOADING: 'SET_LOADING',
    FILTER_VIDEOGAME_LIST: 'FILTER_VIDEOGAME_LIST',
    FILL_VIDEOGAME_LIST: 'FILL_VIDEOGAME_LIST',
    FILTER_VIDEOGAME_BY_PLATFORM: 'FILTER_VIDEOGAME_BY_PLATFORM',
    FILL_VIDEOGAME_BY_PLATFORM_LIST: 'FILL_VIDEOGAME_BY_PLATFORM_LIST',
    FILL_FULL_VIDEOGAME_LIST: 'FILL_FULL_VIDEOGAME_LIST',
    SORT_VIDEOGAMES_BY_DATE: 'SORT_VIDEOGAMES_BY_DATE',
    SORT_CARD_VIDEOGAMES: 'SORT_CARD_VIDEOGAMES',
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_LOGOUT_ERROR: 'AUTH_LOGOUT_ERROR',
    ADD_USER: 'ADD_USER',
    ADD_USER_ERROR: 'ADD_USER_ERROR',
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
}

export default actionTypes;