const actionTypes = {
    LOAD_VIDEOGAMES: 'LOAD_VIDEOGAMES',
    LOAD_VIDEOGAMES_ERROR: 'LOAD_VIDEOGAMES_ERROR',
    LOAD_VIDEOGAME: 'LOAD_VIDEOGAME',
    LOAD_VIDEOGAME_ERROR: 'LOAD_VIDEOGAME_ERROR',
    SET_LOADING: 'SET_LOADING',
    FILTER_VIDEOGAME_LIST: 'FILTER_VIDEOGAME_LIST',
    FILL_VIDEOGAME_LIST: 'FILL_VIDEOGAME_LIST'
}

export default actionTypes;