const actionTypes = {
    LOAD_VIDEOGAMES: 'LOAD_VIDEOGAMES',
    LOAD_VIDEOGAMES_ERROR: 'LOAD_VIDEOGAMES_ERROR',
    LOAD_VIDEOGAME: 'LOAD_VIDEOGAME',
    LOAD_VIDEOGAME_ERROR: 'LOAD_VIDEOGAME_ERROR',
    SET_LOADING: 'SET_LOADING',
    FILTER_VIDEOGAME_LIST: 'FILTER_VIDEOGAME_LIST',
    FILL_VIDEOGAME_LIST: 'FILL_VIDEOGAME_LIST',
    FILTER_VIDEOGAME_BY_PLATFORM: 'FILTER_VIDEOGAME_BY_PLATFORM',
    FILL_VIDEOGAME_BY_PLATFORM_LIST: 'FILL_VIDEOGAME_BY_PLATFORM_LIST',
    FILTER_VIDEOGAME_BY_SALE: 'FILTER_VIDEOGAME_BY_SALE',
    FILL_VIDEOGAME_BY_SALE_LIST: 'FILL_VIDEOGAME_BY_SALE_LIST',
}

export default actionTypes;